language: node_js
node_js:
  - lts/boron
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: bf+QWMPaNXJaoP5NVDWo0Ag5T43HSm7hK322YSUu32hMXRy7qZjcoly25/syi1MdB/llC6oHb/8zQ4SwCZde4tsY0H7hAAJQtb+lbYnk7cYaUD8Oj3BW8A9lzAk8XegJhLHCb3oXnf7Bgate/BOYDxMjksmdcWjiwhkFoDOulvBv+ooEY4FzCqtLZwKHlRGxIpTCLvn9DGVolyyxpCKhFfD8nVjd1RKqw59i+XnIBwRTR3v2GGuhqPWQwDSUH3/gZgRPxRIgpE38T96rE44y0GmQnIVw9QROHL7BzEH0N5iTUPN8riBh93bx05pDhDFMPZlIPvy/hsX4V/S3R9eaFDSjpiiu4EPRjEbXrgt3/I5dMsYh1z0VdHPiZCdQLV48oqpkOKhZk8Uxsk87R3h/qxTuCN98wzSQVOvcNjIMJ8aZpWuq9iaQuLcgleCnuJT/b+hY36M0V7QzdGAC5Plimnoshy6EDIavZ2Dnny2oiKlU5uX7xNrtRfYEe48/gH5H/r1WP9MNwiJa+KAhNdqRCje2ZTDtC+ddCryAmBKyyo6dX6go9vjQYNDdGDBHH34MIuVb1cWsXdoJ53kaEFiM0ssB0n31HHcX8CcK8cGRfN+1DVGiGNYY/BpDB0D7Xzw2DpjHdUnFuITxkldHOzpxbyyqdKhAOGc+hGY1ILyRVME=
  file:
    - 'iso-15924.js'
    - 'iso-15924.min.js'
  on:
    tags: true
